# Site settings
title: UC Davis Commencement
email: help@help.com
description: > # this means to ignore newlines until "baseurl:"
  This is a Jekyll Starter template developed by cydoval.com.
subject: UC Davis Starter template for CAES CRU and anyone else
classification: Web Design

permalink: pretty

paginate: 3

# Build settings
markdown: kramdown

#gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
